[package]
name = 'tidywater'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'tidywater'

[dependencies]
extendr-api = '0.8.1'
roots = "0.0.8"

[profile.release]
lto = true
codegen-units = 1
