name: 'Format R code with air'
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  
jobs:
  air-format:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT

    - name: Pull latest changes
      run: |
        git pull origin ${{ steps.extract_branch.outputs.branch }}

    - name: Commit changes
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Format R code
      uses: rstudio/shiny-workflows/format-r-code@v1

    - name: Push changes
      run: |
        git push origin HEAD:${{ steps.extract_branch.outputs.branch }}